### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by Eanders1**
progress bar

### CODE REVIEW

**Comment by Eanders1** [comment]
I added an example of how the progress bar looks like

**Comment by brembs** [comment]
It looks to me as if this progress bar runs for each group, not in total? So it starts fresh with each new group, correct?

**Comment by Eanders1** [comment]
Tha i

> It looks to me as if this progress bar runs for each group, not in total? So it starts fresh with each new group, correct?

This is true. I'll figure out a way to update it to include both groups

**Comment by Eanders1** [comment]
It should now use the total fly number for both groups

**Comment by brembs** [comment]
Looks like it. I'll merge it and test...

**Comment by brembs** [comment]
It stopped at "100% completed, 2 flies left" :-D

**Pull request merged**
