### PR TITLE
Progress bar for data integrity

### PR DESCRIPTION
**Pull request by Eanders1**
I came by a function called TxtProgressbar. It displays the progress of a for loop in the console. I implemented it to track the progress of the data integrity function. Let me know what you think! It also does not require any additional libraries so I removed the magick one in this example.
I changed the progress indicator to display "DTS", because why not.

### CODE REVIEW

**Comment by brembs** [comment]
Sounds cool!
It would need to be in both loops then, one for the metadata and one for the duplicate raw data...

**Comment by brembs** [comment]
Moreover, there is so much going on in the console, it'll will be hard to pay attention to it. But I'll try it out in combination with the animated gif, let's see.

**Comment by Eanders1** [comment]
I agree, but the console feed is "pausing" when it is running the MultiFlyDataVerification and MultiFlyDuplicateCheck.

**Comment by brembs** [comment]
True. I now found other solutions I'll try.

**Comment by brembs** [comment]
One could also think about putting these bars in each group loop...

**Comment by brembs** [comment]
Tried it in the group loop, but it gets overwritten.

**Comment by brembs** [comment]
Implemented a different one in the group loop. Works nicely: creates a little window with a progress bar :-)

**Comment by Eanders1** [comment]
Where did you make the changes? Can I try them?

**Comment by brembs** [comment]
Yes, this branch: https://github.com/brembslab/DTSevaluations/tree/single-folder

**Comment by brembs** [comment]
If you check the branch I created, you'll see I already have that change in there...

**Pull request closed without merging**
