### PR TITLE
Replaced "project" to "dataset"

### PR DESCRIPTION
**Pull request by AnEhw**
I'm not 100% sure if this is the wanted result, but i just replaced "project" to "dataset" in all of the evaluation files.

### CODE REVIEW

**Comment by brembs** [comment]
If you have tested it with the various datasets we have and it works (i.e., project.Rmd is renamed to dataset.Rmd), then we're almost there. Need to also fix it in dts_datamodel (different repo).

**Comment by AnEhw** [comment]
I tested it with the colorlearning, switch, t-learning and one of my datasets. It seems to work fine. 

There is a error with the OM_joystick data set, but this is the same with the current version:
```
Quitting from lines 24-37 (single_fly.Rmd) 
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
```
But i have not looked into it yet.

**Comment by brembs** [comment]
OK, looks good. Need to fix the OM-Joystick dataset. In fact, we should replace this one with one of Simon's datasets and see what happens...

**Review by brembs — APPROVED** [review]
Should work, can be merged

**Pull request merged**
