### PR TITLE
Automated script for creating xml

### PR DESCRIPTION
**Pull request by AnEhw**
Till now the files from the shiming-setup had to be pasted by hand. Now the script takes the two output files from the shiming set-up and creats xml-files for the analysis. A line has to be added to the read.xml file due to the row counter beeing also pasted in and considered as variable. I could not find a way to avoid it. So it has to be removed when reading in the data. This works fine.
The file also writes all the names in one template yml file, so the names dont need to be put in by hand. But it dose not conider groups. This still saves time and avoid typing erros.
Since i'm the only one who will use it for now, i dont know if we want to have it in the master branch.

### CODE REVIEW

**Comment by brembs** [comment]
I don't think we need to merge it, but will have a look at the code!

**Comment by brembs** [comment]
We may merge it if we are publishing your raw data and need to explain how it as generated.

**Comment by AnEhw** [comment]
For this code to work i still need the small change to the read.xml file. Shuld i make a pull request then, without the other files?

**Comment by brembs** [comment]
Let's wait until our meeting, I still need to think about it and discuss it with you two.

**Pull request closed without merging**
